server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/   # 前缀
    suffix: .html   # 后缀
  datasource:
    username: root
    password: hc2919
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_chatter?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    hikari:
      minimum-idle: 5   # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true   # 自动提交
      idle-timeout: 1000000  # 连接超时的最大时长（毫秒），超时则被释放（retired）,默认：10分钟
      pool-name: hikariCP     # 连接池名字
      max-lifetime: 30000     # 连接的生命时长（毫秒）超时而且没被使用则被释放（retired）,默认：30分钟 1800000ms
      connection-timeout: 30000   # 等待连接池分配连接的最大时长（毫秒）,超过这个时长还没可用的连接则发生SQLException,默认30秒
      connection-test-query: SELECT 1
  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/,classpath:/public/  # classpath:/META-INF/resources/,
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
    hiddenmethod:
      filter:
        enabled: true   # 设置开启RESTFul风格
  servlet:
    multipart:
      max-file-size: 500KB  # 设置文件上传大小的限制
      max-request-size: 2MB # 文件最大请求限制，用于批量
  mail:
    host: smtp.tom.com
    username: fz2919
    password: 123456
    protocol: smtp
    default-encoding: UTF-8
    port: 8081

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml   # 所有 mapper 映射的文件所在目录位置 cn/peyton/children/chatter/
  type-aliases-package: cn.peyton.children.chatter.pojo   # 所有数据库表逆向后所--映射的实体类 Entity/Bean/POJO
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开启 mybatis 的日志实现，可以在控制台打印输入 SQL 语句，开发环境配置